import { readFileSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
const measure = path => { const bytes = readFileSync(path), gzip = gzipSync(bytes).length; console.log(`${path}: ${(bytes.length / 1024).toFixed(2)} KiB, ${(gzip / 1024).toFixed(2)} KiB gzip`); return gzip; };
// The 20 KiB budget covers the core editor + CSS only. Opt-in IO (@fsaldivar.dev/diagram/io) is reported but not counted.
const core = measure('packages/diagram/dist/diagram.js') + measure('packages/diagram/dist/style.css');
console.log(`Core + CSS: ${(core / 1024).toFixed(2)} KiB gzip. Runtime dependencies: 0.`);
const io = measure('packages/diagram/dist/io.js');
console.log(`Opt-in IO (@fsaldivar.dev/diagram/io): ${(io / 1024).toFixed(2)} KiB gzip (not counted against the core budget).`);
const convert = measure('packages/diagram/dist/convert.js');
console.log(`Opt-in convert (@fsaldivar.dev/diagram/convert): ${(convert / 1024).toFixed(2)} KiB gzip (not counted; parseAny/convertText/detectFormat/tryParse).`);
const markdown = measure('packages/diagram/dist/markdown.js');
console.log(`Opt-in markdown (@fsaldivar.dev/diagram/markdown): ${(markdown / 1024).toFixed(2)} KiB gzip (not counted; mermaidToSvg/enhanceMarkdown).`);
const layout = measure('packages/diagram/dist/layout.js');
console.log(`Opt-in layout (@fsaldivar.dev/diagram/layout): ${(layout / 1024).toFixed(2)} KiB gzip (not counted; auto/organic/radial).`);
const exportBundle = measure('packages/diagram/dist/export.js');
console.log(`Opt-in export (@fsaldivar.dev/diagram/export): ${(exportBundle / 1024).toFixed(2)} KiB gzip (not counted; SVG/PNG/HTML/legend/TikZ).`);
const analysis = measure('packages/diagram/dist/analysis.js');
console.log(`Opt-in analysis (@fsaldivar.dev/diagram/analysis): ${(analysis / 1024).toFixed(2)} KiB gzip (not counted against the core budget).`);
const element = measure('packages/diagram/dist/element.js');
console.log(`Opt-in Web Component (@fsaldivar.dev/diagram/element): ${(element / 1024).toFixed(2)} KiB gzip (not counted; pulls core).`);
const labels = measure('packages/diagram/dist/labels.js');
console.log(`Opt-in labels (@fsaldivar.dev/diagram/labels): ${(labels / 1024).toFixed(2)} KiB gzip (not counted; no deps).`);
const player = measure('packages/diagram/dist/player.js');
console.log(`Opt-in path player (@fsaldivar.dev/diagram/player): ${(player / 1024).toFixed(2)} KiB gzip (not counted; decoupled).`);
const minimap = measure('packages/diagram/dist/minimap.js');
console.log(`Opt-in minimap (@fsaldivar.dev/diagram/minimap): ${(minimap / 1024).toFixed(2)} KiB gzip (not counted; public API only).`);
const recovery = measure('packages/diagram/dist/recovery.js');
console.log(`Opt-in recovery (@fsaldivar.dev/diagram/recovery): ${(recovery / 1024).toFixed(2)} KiB gzip (not counted; host-owned storage).`);
const themes = measure('packages/diagram/dist/themes.js');
console.log(`Opt-in themes (@fsaldivar.dev/diagram/themes): ${(themes / 1024).toFixed(2)} KiB gzip (not counted; pure data).`);
const templates = measure('packages/diagram/dist/templates.js');
console.log(`Opt-in templates (@fsaldivar.dev/diagram/templates): ${(templates / 1024).toFixed(2)} KiB gzip (not counted; starter documents).`);
const react = measure('packages/diagram/dist/react.js');
console.log(`Opt-in React wrapper (@fsaldivar.dev/diagram/react): ${(react / 1024).toFixed(2)} KiB gzip (not counted; React external, bundles core).`);
const vue = measure('packages/diagram/dist/vue.js');
console.log(`Opt-in Vue wrapper (@fsaldivar.dev/diagram/vue): ${(vue / 1024).toFixed(2)} KiB gzip (not counted; Vue external, bundles core).`);
const svelte = measure('packages/diagram/dist/svelte.js');
console.log(`Opt-in Svelte action (@fsaldivar.dev/diagram/svelte): ${(svelte / 1024).toFixed(2)} KiB gzip (not counted; no deps, bundles core).`);
const globalBuild = measure('packages/diagram/dist/kairo.global.js');
console.log(`Standalone global (dist/kairo.global.js): ${(globalBuild / 1024).toFixed(2)} KiB gzip (self-contained IIFE; not counted).`);
if (core > 20 * 1024) throw new Error('Core + CSS exceeds the 20 KiB gzip budget.');
